# -*- coding: utf-8 -*-
"""AI_FIN.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MZMTFRHj1ilxWE9BOYPWouQmMPBY2w4x
"""

!pip install streamlit
import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

# ---------------------------
# PAGE CONFIGURATION
# ---------------------------
st.set_page_config(
    page_title="AI Financial Advisory Chatbot",
    page_icon="💰",
    layout="wide"
)

# ---------------------------
# HEADER
# ---------------------------
st.markdown("""
<div style='background-color:#4CAF50;padding:15px;border-radius:10px'>
<h1 style='text-align:center;color:white;'>
💰 AI-Based Financial Advisory Chatbot
</h1>
<p style='text-align:center;color:white;'>
Personalized Financial Guidance Using Generative AI
</p>
</div>
""", unsafe_allow_html=True)

st.write("")

# ---------------------------
# LOGIN SECTION
# ---------------------------
if "logged_in" not in st.session_state:
    st.session_state.logged_in = False

if not st.session_state.logged_in:

    st.subheader("🔐 User Login")

    username = st.text_input("Username")
    password = st.text_input("Password", type="password")

    if st.button("Login"):

        if username == "admin" and password == "admin123":
            st.session_state.logged_in = True
            st.success("Login Successful")
            st.rerun()
        else:
            st.error("Invalid Username or Password")

else:

    # ---------------------------
    # SIDEBAR
    # ---------------------------
    st.sidebar.title("📌 Navigation")

    menu = st.sidebar.radio(
        "Select Module",
        [
            "Home",
            "Financial Analysis",
            "Investment Advice",
            "Loan Eligibility",
            "Reports"
        ]
    )

    # ---------------------------
    # HOME PAGE
    # ---------------------------
    if menu == "Home":

        st.header("🏠 Welcome")

        st.write("""
        This project provides:
        - Budget Analysis
        - Financial Planning
        - Investment Suggestions
        - Loan Eligibility Prediction
        - Report Generation
        """)

        st.info("Use the navigation menu to explore features.")

    # ---------------------------
    # FINANCIAL ANALYSIS
    # ---------------------------
    elif menu == "Financial Analysis":

        st.header("💰 Financial Details")

        income = st.number_input(
            "Monthly Income (₹)",
            min_value=0.0
        )

        expenses = st.number_input(
            "Monthly Expenses (₹)",
            min_value=0.0
        )

        savings = st.number_input(
            "Current Savings (₹)",
            min_value=0.0
        )

        goal = st.selectbox(
            "Financial Goal",
            [
                "Emergency Fund",
                "Buy a House",
                "Retirement",
                "Investment",
                "Education"
            ]
        )

        if st.button("Analyze Financial Status"):

            remaining = income - expenses

            st.subheader("📊 Financial Summary")

            col1, col2, col3 = st.columns(3)

            col1.metric("Income", f"₹{income}")
            col2.metric("Expenses", f"₹{expenses}")
            col3.metric("Balance", f"₹{remaining}")

            st.subheader("🤖 AI Recommendation")

            if remaining <= 0:
                st.error(
                    "Your expenses exceed your income. Reduce spending."
                )

            elif remaining < income * 0.2:
                st.warning(
                    "Savings rate is low. Try saving at least 20% of income."
                )

            else:
                st.success(
                    "Excellent financial management."
                )

            st.subheader("🎯 Goal-Based Suggestions")

            if goal == "Emergency Fund":
                st.write(
                    "Maintain savings equal to 6 months of expenses."
                )

            elif goal == "Buy a House":
                st.write(
                    "Build a down payment fund and improve credit score."
                )

            elif goal == "Retirement":
                st.write(
                    "Invest regularly in retirement schemes."
                )

            elif goal == "Investment":
                st.write(
                    "Diversify investments across SIPs, ETFs and Stocks."
                )

            elif goal == "Education":
                st.write(
                    "Create a long-term education savings plan."
                )

            st.subheader("📈 Expense Distribution")

            labels = ["Expenses", "Savings"]

            sizes = [
                expenses,
                max(remaining, 0)
            ]

            fig, ax = plt.subplots()

            ax.pie(
                sizes,
                labels=labels,
                autopct="%1.1f%%"
            )

            st.pyplot(fig)

    # ---------------------------
    # INVESTMENT ADVICE
    # ---------------------------
    elif menu == "Investment Advice":

        st.header("📈 Investment Recommendations")

        savings_amount = st.number_input(
            "Enter Total Savings (₹)",
            min_value=0.0
        )

        if st.button("Get Suggestions"):

            if savings_amount < 50000:

                st.success(
                    "Recommended: Fixed Deposits and SIPs"
                )

            elif savings_amount < 200000:

                st.success(
                    "Recommended: Mutual Funds and ETFs"
                )

            else:

                st.success(
                    "Recommended: Diversified Portfolio including Stocks"
                )

    # ---------------------------
    # LOAN ELIGIBILITY
    # ---------------------------
    elif menu == "Loan Eligibility":

        st.header("🏦 Loan Eligibility Checker")

        income = st.number_input(
            "Monthly Income",
            min_value=0.0
        )

        expenses = st.number_input(
            "Monthly Expenses",
            min_value=0.0
        )

        if st.button("Check Eligibility"):

            balance = income - expenses

            if income >= 50000 and balance >= 10000:

                st.success(
                    "Eligible for Loan Approval"
                )

            else:

                st.error(
                    "Not Eligible for Loan Approval"
                )

    # ---------------------------
    # REPORTS
    # ---------------------------
    elif menu == "Reports":

        st.header("📄 Download Financial Report")

        income = st.number_input(
            "Income",
            min_value=0.0
        )

        expenses = st.number_input(
            "Expenses",
            min_value=0.0
        )

        savings = st.number_input(
            "Savings",
            min_value=0.0
        )

        if st.button("Generate Report"):

            report = pd.DataFrame({
                "Income": [income],
                "Expenses": [expenses],
                "Savings": [savings]
            })

            csv = report.to_csv(index=False)

            st.download_button(
                label="⬇ Download CSV Report",
                data=csv,
                file_name="financial_report.csv",
                mime="text/csv"
            )

    # ---------------------------
    # FOOTER
    # ---------------------------
    st.markdown("---")
    st.markdown(
        "<center><b>AI-Based Financial Advisory Chatbot Using Generative AI</b></center>",
        unsafe_allow_html=True
    )